title:             Weather Application
email:             sravaniaku11@example.com
description: "this is a app used to give weather details according to given locations"
author: "sravani"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

exclude:
  - LICENSE
  - README.md
  - concept.gif

# Social Profiles
twitter_username: "sranavi"
github_username: "sravaniaku15347"
facebook_username: "sranavi"
